FROM ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian

ENV DEBIAN_FRONTEND=noninteractive

ENV PATH="/root/.cargo/bin:${PATH}"

COPY ./package.json /src2/package.json
WORKDIR /src2
RUN yarn rust:targets

VOLUME ["/src"]
WORKDIR /src/crates/matrix-sdk-crypto-nodejs

CMD yarn install && yarn build:linux
